### PR TITLE
feat: reconfigure uses stale components

### PR DESCRIPTION
**Pull request by PaulFarault**
#### Which issue(s) this PR fixes

Part of #378 

#### Additional comments

- Reconfigure now uses stale component.
- Each deployment updates the stale table.

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by rpignolet — APPROVED** [review]

**Comment by mdrutel** [comment]
Hi,
After executing ```tdp deploy --mock-deploy```, stale components remain stale.
Maybe it's an old behaviour.

**Comment by PaulFarault** [comment]
> After executing tdp deploy --mock-deploy, stale components remain stale.

I assume you meant **some** stale components remain stale. Here is my understanding of the problem:

`tdp stale --generate` relies on the `component_version_log` table to determine which component have been modified. Then, it uses the DAG to determine which of them and which of their dependencies need a `config` and/or `restart` operation. Some components need both `restart` and `config` to be reconfigured, others only a `restart` or only a `config`.

Problem is that the `component_version_log` table is not filled properly. A new version of the component is saved into this table only if it has a `config` AND a `restart` in the SAME deployment. Which means that it won't save properly components that:

- had a `config` and a `restart` in separate deployment;
- need only a `config` or a `restart` to be reconfigured.

`tdp stale --generate` won't see those components as properly reconfigured, hence will still list them as stale.

If that's the problem, I can't fix it without having to modify a lot of the `component_version_log` logic. I opened #384 to discuss an answer to this problem.

**Review by mdrutel — APPROVED** [review]

**Comment by mdrutel** [comment]
Hi,
There's a problem when you modify variables which is bound to a service and not to a component : the service is not tagged as clean, and thus is always tagged as stale.

eg. : hdfs service is deployed the first time : in the table component_version_log, we have :
```
17|1|hdfs||d20df39da11d0c72803cc758aefbe28cdf05d0df
15|1|hdfs|datanode|d20df39da11d0c72803cc758aefbe28cdf05d0df
16|1|hdfs|httpfs|d20df39da11d0c72803cc758aefbe28cdf05d0df
13|1|hdfs|journalnode|d20df39da11d0c72803cc758aefbe28cdf05d0df
14|1|hdfs|namenode|d20df39da11d0c72803cc758aefbe28cdf05d0df
```
I change 1 value in tdp_vars/hdfs/hdfs.yml 
```
$ git log
commit e8734bfa0975899fb59adbcda3ee25292dbd6827 (HEAD -> master)
Date:   Mon Aug 7 08:01:46 2023 +0200
    test

commit d20df39da11d0c72803cc758aefbe28cdf05d0df
Date:   Mon Aug 7 07:59:03 2023 +0200
    add variables from tdp
```
I generate the stale components with ```tdp stale --generate``` :
```
service_name    component_name              to_reconfigure    to_restart
--------------  --------------------------  ----------------  ------------
hdfs            datanode                    True              True
hdfs            httpfs                      True              True
hdfs            jmx-exporter                True              False
hdfs            journalnode                 True              True
hdfs            namenode                    True              True
hdfs            client                      True              False
hdfs            ranger                      True              False
```
I deploy the generated plan :
```
tdp plan reconfigure
tdp deploy --mock-deploy
```
Result :
```
sqlite> select deployment_id, service, component, version from component_version_log where service = 'hdfs' order by deployment_id;
1|hdfs||d20df39da11d0c72803cc758aefbe28cdf05d0df
1|hdfs|datanode|d20df39da11d0c72803cc758aefbe28cdf05d0df
1|hdfs|httpfs|d20df39da11d0c72803cc758aefbe28cdf05d0df
1|hdfs|journalnode|d20df39da11d0c72803cc758aefbe28cdf05d0df
1|hdfs|namenode|d20df39da11d0c72803cc758aefbe28cdf05d0df
2|hdfs|datanode|e8734bfa0975899fb59adbcda3ee25292dbd6827
2|hdfs|httpfs|e8734bfa0975899fb59adbcda3ee25292dbd6827
2|hdfs|journalnode|e8734bfa0975899fb59adbcda3ee25292dbd6827
2|hdfs|namenode|e8734bfa0975899fb59adbcda3ee25292dbd6827
```
There's no line for the service 'hdfs' like :
```
2|hdfs||e8734bfa0975899fb59adbcda3ee25292dbd6827
```

**Review by mdrutel — APPROVED** [review]
I tested multiples stale : component level and service level => everything was OK ^^

**Review by rpignolet — APPROVED** [review]

**Pull request merged**
