### PR TITLE
feat: held status after fail

### LINKED ISSUE #337: Operations status remain PLANNED even after a FAILURE
As discovered by @sergkudinov, when an operation fails, we've got:

```txt
SUCCESS
SUCCESS
FAILURE
PLANNED
PLANNED
```

in the database instead of:

```txt
SUCCESS
SUCCESS
FAILURE
HELD
HELD
```

This means that the DeploymentIterator is stopping instead of updating the status of the remaining operations in the database.

### PR DESCRIPTION
**Pull request by PaulFarault**
#### Which issue(s) this PR fixes

Fixes #337 

#### Additional comments

I also added some comments and refactored some of the variables to improve code comprehension.

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by sergkudinov** [comment]
When operations complete with `SUCCESS` in the middle of a deployment execution and the deployment is interrupted (by CTRL + C for example), the deplyment keeps status `RUNNING` and the rest of operations keep `PLANNED`.

It is easy to reproduce in `--mock-deploy`:

1. `tdp plan dag`
2. `tdp deploy --mock-deploy`
3. Interrupt with `CTRL+C` in the middle

Probably, it also works when interrupted in between of operations in real mode.

**Review by sergkudinov — CHANGES_REQUESTED** [review]
add functionality described in my comment above

**Comment by PaulFarault** [comment]
@sergkudinov that's an other issue: https://github.com/TOSIT-IO/tdp-lib/issues/340

**Review by sergkudinov — APPROVED** [review]

**Review by sergkudinov — APPROVED** [review]

**Review by mdrutel — APPROVED** [review]
Test is OK

**Pull request merged**
