### PR TITLE
[doc] Minor fix docstrings

### PR DESCRIPTION
**Pull request by sergkudinov**
#### Which issue(s) this PR fixes

None

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by PaulFarault — APPROVED** [review]

**Review by jpsavy — COMMENTED** [review]
One might want to rename the deployment_log attribute to _deployment_log so that it has a name consistent with the other static attributes (such as: _operations or _run_operation) of the DeploymentIterator class.

**Review by jpsavy — COMMENTED** [review]
The deployment_log attribute could be prefixed with "_" in another PR: like 'Prefix deployment_log attribute with "_"'

**Review by rpignolet — APPROVED** [review]

**Comment by PaulFarault** [comment]
@jpsavy The `_deployment_log` attribute has a getter and a setter (through the `@property` decorator), which means that we can access with `DeploymentPlan.deployment_log`.

Hence, it's not really an attribute but it has the same behavior so I think that's ok.

The true question may be "Why do we use a `@property` here?", it doesn't seem useful in this case. Any thoughts @rpignolet?

However, it is not related to this PR so we can merge it.

**Review by jpsavy — APPROVED** [review]

**Comment by rpignolet** [comment]
@sergkudinov Please, resolve conflicts.

**Pull request merged**
