### PR TITLE
fix: to_restart and to_config in get_hosted_entity_statuses

### PR DESCRIPTION
**Pull request by SteBaum**
#### Which issue(s) this PR fixes

Fixes None

The `to_restart` and `to_config` indicators must be true only if component is active, otherwise if it belongs to a node that has been decommissioned there is no point to restart or reconfigure it and it will fail anyways since the host is not there anymore. Therefore an additional condition has been put for these indicators to be true.

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by PaulFarault** [comment]
Seems ok, please add a comment and/or something in the docstring.

**Comment by SteBaum** [comment]
> Seems ok, please add a comment and/or something in the docstring.

Has been done.

**Comment by PaulFarault** [comment]
Well, I spoke too soon. Why make the reading of the `to_restart` and `to_config` columns depend on the `is_active` column?

Can't we just use the `filter_active` filter to only select "truly" configurable/restartable components instead of altering values on read?

**Comment by SteBaum** [comment]
> Well, I spoke too soon. Why make the reading of the `to_restart` and `to_config` columns depend on the `is_active` column?
> 
> Can't we just use the `filter_active` filter to only select "truly" configurable/restartable components instead of altering values on read?

It is not only altering values on read but also on write when doing the `tdp plan reconfigure` command. Yes, it is possible to put the `filter_active` to True in the script of the`tdp plan reconfigure` command. However, the reason I put it in the query `get_hosted_entity_statuses` is that I thought it would always be illogical to restart or configure a component which is on a host that does not exist anymore so it was logical to condition the values of these two columns on whether the component actually exists or not.

**Comment by PaulFarault** [comment]
Ok, just use the `filter_active` where it's needed then!

**Comment by SteBaum** [comment]
> Ok, just use the `filter_active` where it's needed then!

Done

**Review by PaulFarault — APPROVED** [review]

**Comment by SteBaum** [comment]
is_active column has been removed

**Pull request closed without merging**
