### PR TITLE
feat(cli/playbooks): add --for-collection option

### LINKED ISSUE #235: Add option to playbooks command to generate meta for additional collection like extras
Currently, when running `tdp playbooks` it generate a `meta` directory with all playbooks from all collections configured with `--collection-path`. If we want to generate `meta` directory for additional collection like extras and only specify this collection inside `--collection-path` it will fail to generate playbooks because the DAG will have missing nodes from core collection.

All collections should be specified inside `--collection-path` and `tdp playbooks` command should have an option to output inside `meta` directory only playbooks from specified collection.

### PR DESCRIPTION
**Pull request by rpignolet**
`--for-collection` option generate meta playbooks only for specific collections (can be multiple)

Generate meta for `tdp-collection`:
```
tdp playbooks --for-collection tdp
```

Generate meta for `tdp-collection-extras`:
```
tdp playbooks --for-collection tdp_extra
```

#### Which issue(s) this PR fixes

Fixes #235 

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by gboutry — APPROVED** [review]

**Comment by leopaul36** [comment]
Not sure why but with tdp-getting-started both `tdp playbooks --for-collection tdp` and `tdp playbooks --for-collection tdp_extra` are giving me a `meta` dir with empty playbooks as a results

**Comment by rpignolet** [comment]
> Not sure why but with tdp-getting-started both `tdp playbooks --for-collection tdp` and `tdp playbooks --for-collection tdp_extra` are giving me a `meta` dir with empty playbooks as a results

It give me a `meta` dir with empty playbooks when using `tdp playbooks` without option but with `--for-collection tdp` or `--for-collection tdp_extra` it is working for me. Do you have a correct `.env` with correct `TDP_COLLECTION_PATH` defined ?

For push is for fix the problem without option.

**Comment by leopaul36** [comment]
> > Not sure why but with tdp-getting-started both `tdp playbooks --for-collection tdp` and `tdp playbooks --for-collection tdp_extra` are giving me a `meta` dir with empty playbooks as a results
> 
> It give me a `meta` dir with empty playbooks when using `tdp playbooks` without option but with `--for-collection tdp` or `--for-collection tdp_extra` it is working for me. Do you have a correct `.env` with correct `TDP_COLLECTION_PATH` defined ?
> 
> Force push is for fix the problem without option.

I figured out my issue. I have the collections as symbolic links in my environment:

```
tdp-getting-started-ln git:(master) ✗ ll ansible_collections/tosit 
total 16K
lrwxrwxrwx 1 leo leo 33 Jan 31 10:58 tdp -> /home/leo/TOSIT-FR/tdp-collection
lrwxrwxrwx 1 leo leo 40 Nov  7 14:21 tdp_extra -> /home/leo/TOSIT-FR/tdp-collection-extras
lrwxrwxrwx 1 leo leo 36 Jan 30 16:15 tdp_observability -> /home/leo/TOSIT-FR/tdp-observability
lrwxrwxrwx 1 leo leo 47 Nov  7 14:21 tdp_prerequisites -> /home/leo/TOSIT-FR/tdp-collection-prerequisites
```

It works when I make a hard copy of the collection in the `ansible_collections/tosit` dir.

**Comment by rpignolet** [comment]
The collection name to use for `--for-collection` option is the directory name I think so if you use `tdp playbooks --for-collection tdp-collection` it should works.

**Comment by leopaul36** [comment]
> tdp-collection

Indeed it works like this :+1:

**Review by leopaul36 — APPROVED** [review]

**Pull request merged**
