### PR TITLE
`browse` the last deployments

### LINKED ISSUE #616: `tdp browse` should show last X deployments instead of first X
When you have more deployments than the limits (by default 15), `tdp browse` only shows the first X deployments (X being the limit).

It should show the last X deployments. Last deployment should be on bottom of list.

### PR DESCRIPTION
**Pull request by SteBaum**
#### Which issue(s) this PR fixes

Fixes #616

#### Additional comments

Changed the order in query. Now showing the deployments in descending order.

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by PACordonnier** [comment]
Thanks @SteBaum. I just tried and it works. I reconsider what I said during the meeting and would rather have the most recent deployment at the end of the output, it makes more sense in a CLI. @rpignolet was right ! Can you modify it ?

Also, I think this is a fix rather than a refactor.

**Comment by rpignolet** [comment]
We should talk about it with @PaulFarault how to fix that (find the good query to do the job)

**Comment by SteBaum** [comment]
@PACordonnier see if it suits you now. The query returns the last deployments (15 by default) in ascending order.

**Comment by PACordonnier** [comment]
Works perfect thanks

**Review by PACordonnier — APPROVED** [review]

**Comment by PaulFarault** [comment]
> We should talk about it with @PaulFarault how to fix that (find the good query to do the job)

This is the correct query to modify. However, I'm unsure why a subquery is being introduced here.

**Review by PaulFarault — CHANGES_REQUESTED** [review]
> We should talk about it with @PaulFarault how to fix that (find the good query to do the job)

This is the correct query to modify. However, I'm unsure why a subquery is being introduced here.

**Review by PaulFarault — APPROVED** [review]

**Review by rpignolet — APPROVED** [review]

**Pull request merged**
