### PR TITLE
Improve dev tools

### PR DESCRIPTION
**Pull request by PaulFarault**
#### Which issue(s) this PR fixes

Fixes None

#### Additional comments

- Add Ruff and it's related GitHub Action (in check mode).
- Replace isort with Ruff "I" rule.
- Remove pre-commit and replace its config with Ruff "E" and "W" rules.
- Create `precommit` task that runs Black and Ruff (in fix mode) and update Readme accordingly.
- Upgrade dev dependencies.
- Remove unused Black configuration.
- Lint files that needed it.

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by sergkudinov — APPROVED** [review]
it seams ok to me

**Review by mdrutel — APPROVED** [review]
tested OK

**Comment by PaulFarault** [comment]
Force pushed after renaming `precommit` task to `precommit-fix` according to @rpignolet suggestion.

**Comment by PaulFarault** [comment]
Rebased on master.

**Review by rpignolet — APPROVED** [review]

**Pull request merged**
