### PR TITLE
Remove deprecated types

### LINKED ISSUE #369: Fix types when migrating to Python 3.9
Upgrading to Python 3.9 allows us to fix a lot of types. In particular:

- Remove `OrderedDict`
- Explicit the correct types for classes that inherit from the `Mapping` abc (as `Collections`)
- Use `list` instead of `List`
- etc

### PR DESCRIPTION
**Pull request by PaulFarault**
#### Which issue(s) this PR fixes

Fixes #369

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by PaulFarault** [comment]
Force pushed after resolving rebase conflicts.

**Comment by mdrutel** [comment]
There's a reference to ```Tuple``` type in the file ```tdp/core/models/base.py```.
Is it concerned by this PR ?

**Comment by PaulFarault** [comment]
> Is it concerned by this PR ?

I rebased again on the last version of master and it should be ok now @mdrutel

**Review by mdrutel — APPROVED** [review]
The tests are OK.
The review of the code seems OK for me.

**Comment by jpsavy** [comment]
Not anymore "Tuple" nor "MappingType" types.

**Comment by jpsavy** [comment]
Generator is now used in place of Iterator for getting SQLAlchemy session

**Review by jpsavy — APPROVED** [review]

**Comment by PaulFarault** [comment]
Last PR added a `from typing import Iterable`. I'll have to rebase one last time before merging this one.

**Comment by PaulFarault** [comment]
Force pushed after rebase.

**Pull request merged**
