### PR TITLE
chore: update python to 3.9 and ansible-core to 2.15.1

### LINKED ISSUE #329: Update Python and Ansible versions
Following https://github.com/TOSIT-IO/tdp-collection/issues/773 and https://github.com/TOSIT-IO/tdp-collection/issues/774, we would need to update Python and ansible-core version here before working on the hosts (see #307).

### PR DESCRIPTION
**Pull request by rpignolet**
#### Which issue(s) this PR fixes

Fixes #329 

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by PaulFarault** [comment]
We may wan't to do something with the `validate`. We could either:

- add an envvar and set it to false in tdp-getting-started
- set default to false
- mention it in the README

Those suggestions are meant to be temporary, the time to fix the JSON schema.

**Comment by PaulFarault** [comment]
> We may want to do something with `--no-validate`.

My commit fix it so it is not a pb anymore. This PR seems to be ready as a minimal upgrade. There are still things to migrate but we could do it incrementally.

**Comment by PaulFarault** [comment]
> We could change for ansible 2.15.0 > if required later.

I'm not sure to understand your comment. `ansible-core` has been set to 2.15.1 (you can see that on the `pyproject.toml`). Did you meant on the README or other?

**Review by PaulFarault — APPROVED** [review]

**Comment by gonzaloetjo** [comment]
> > We could change for ansible 2.15.0 > if required later.
> 
> I'm not sure to understand your comment. `ansible-core` has been set to 2.15.1 (you can see that on the `pyproject.toml`). Did you meant on the README or other?

It's related to what I believe @rpignolet was saying, about testing with ansible-core > 2.15.0 instead of a fixed version.

**Pull request merged**
