### PR TITLE
fix: render correct filter pattern

### LINKED ISSUE #206: Regex filter are not well represented in database
After executing ```tdp restart-required --dry```, I got ```re.compile('.+_(config|start)')``` in ```filter``` field in the output of ```tdp browse```:
```
Deployments:
  id  sources    targets                 filter                           start             end               state    services
----  ---------  ----------------------  -------------------------------  ----------------  ----------------  -------  -----------------------------------------------------------------------
   1  None       zookeeper_server_start  zookeeper_server_start           2022-08-09 [...]  2022-08-09 [...]  Success  zookeeper
   2             None                    re.compile('.+_(config|start)')  2022-08-09 [...]  2022-08-09 [...]  Success  exporter,hadoop,hbase,hdfs,hive,knox,ranger,spark,spark3,yarn,zookeeper
```

_Originally posted by @kpgtek in https://github.com/TOSIT-IO/tdp-lib/issues/205#issuecomment-1209569892_

### PR DESCRIPTION
**Pull request by gboutry**
fix #206

### CODE REVIEW

**Comment by rpignolet** [comment]
What is the result in the database ?

**Comment by gboutry** [comment]
> What is the result in the database ?

`.+_(config|start)`

**Comment by rpignolet** [comment]
When we read a deployment in the database, how do we know if this is a regex or a glob pattern ?

**Comment by gboutry** [comment]
> When we read a deployment in the database, how do we know if this is a regex or a glob pattern ?

Added filter type in deploymentlog model

**Review by rpignolet — APPROVED** [review]

**Review by kpgtek — APPROVED** [review]

**Pull request merged**
